### PR TITLE
fix: Don't infinitely loop on pinned tabs

### LINKED ISSUE #21: Freeze on tab close/switch
Closing a tab or switching between open tabs freezes the editor while this plugin is enabled. I tried looking at the console, but there's no useful output regarding the issue (to my non-web dev eyes).

Repro is simple - install, enable, and try closing an open tab or switching to another one.

### PR DESCRIPTION
**Pull request by bb010g**
Fixes #21.

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -41,8 +41,8 @@ export default class CursorLocation extends Plugin {
   }
 
   private updateShowStatus() {
-    const mode: string = this.app.workspace.getLeaf().getViewState()
-      .state?.mode;
+    const mode: string = this.app.workspace.getActiveViewOfType(obsidian.WorkspaceLeaf)
```
Comment (swar8080) [inline src/main.ts:44]: Hey @bb010g, did you mean to use `this.app.workspace.getActiveViewOfType(View)` here, like you mentioned in https://github.com/spslater/obsidian-cursor-location-plugin/issues/21#issuecomment-1633526889? That fixes the problem for me

 `this.app.workspace.getActiveViewOfType(obsidian.WorkspaceLeaf)` does not compile

Comment (bb010g) [reply src/main.ts]: Sorry for the delay. You're correct; I transferred this from my live edits in `.obsidian` wrong. Thanks for catching it.
